import type { NextPage } from 'next'
import Head from 'next/head'
import Input from '@gloryshop/Input/Input'
import Image from 'next/image'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container' >
         <h1 className='font-bold text-center mt-8'>  WElcome new project</h1>
          <button className='bg-[red] mx-auto px-atuo py-2 block mt-4  rounded-lg text-white px-4'>click here</button>
          <Input />
     </main>
    </div>
  )
}

export default Home
